engines:
  pep8:
    enabled: true
    checks:
      W191:
        enabled: false
ratings:
   paths:
   - "**.py"

exclude_paths:
- archive/
- debian_packages/
- docs/
- clips/
- tests/
- pics/
- mechanical/
