doc-warnings: no
test-warnings: no
strictness: medium
autodetect: yes
pylint:
    disable:
        # - logging-too-many-args
        - too-many-function-args
        - Too-many-locals
        # - unused-import
        # - pointless-string-statement
        # - R0914

ignore-paths:
    - Archive_2017

python-targets:
    - 2
    - 3
