#!/bin/bash
python robocontrol.py &
cd /usr/src/mjpg-streamer/mjpg-streamer/mjpg-streamer-experimental &
./mjpg_streamer -o "output_http.so -w ./www" -i "input_raspicam.so -x 640 -y 48
0 -fps 20 -ex night -vf yes" &